// Code generated by redwood. DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"strings"

	"github.com/urfave/cli/v3"

	commands "go.cadenya.com/cadenya-cli/internal/commands"
)

func workspaceAdminCommand() *cli.Command {
	return &cli.Command{
		Name:                      "workspace-admin",
		DisableSliceFlagSeparator: true,
		Commands: []*cli.Command{
			{
				Name:                      "list-profiles",
				DisableSliceFlagSeparator: true,
				Usage:                     "Search account profiles",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.Int32Flag{Name: "limit", Usage: "Maximum number of results to return"},
					&cli.StringFlag{Name: "cursor", Usage: "Pagination cursor from previous response"},
					&cli.StringFlag{Name: "query", Usage: "Free-form search over profile name and email. Case-insensitive substring match; empty returns all profiles."},
					&cli.StringFlag{Name: "labels", Usage: "Filters by metadata labels. Comma-separated key=value pairs, e.g. \"env=prod,team=ai\". A resource matches only if every pair matches exactly (AND semantics)."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "TYPE", path: []string{"spec", "type"}}}
					var converted commands.WorkspaceAdminListProfilesConversion
					if err := commands.ConvertWorkspaceAdminListProfiles(cmd, &converted); err != nil {
						return err
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					page, err := client.WorkspaceAdmin().ListProfiles(ctx, &converted.Params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, true, map[string]any{"items": page.Items, "nextCursor": page.NextCursor})
				},
			},
			{
				Name:                      "list-account",
				DisableSliceFlagSeparator: true,
				Usage:                     "List all workspaces in the account",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.Int32Flag{Name: "limit", Usage: "Maximum number of results to return"},
					&cli.StringFlag{Name: "cursor", Usage: "Pagination cursor from previous response"},
					&cli.BoolFlag{Name: "include-archived", Usage: "When true, archived workspaces are included in the results. Defaults to false (active workspaces only)."},
					&cli.StringFlag{Name: "labels", Usage: "Filters by metadata labels. Comma-separated key=value pairs, e.g. \"env=prod,team=ai\". A resource matches only if every pair matches exactly (AND semantics)."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}}
					var converted commands.WorkspaceAdminListAccountConversion
					if err := commands.ConvertWorkspaceAdminListAccount(cmd, &converted); err != nil {
						return err
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					page, err := client.WorkspaceAdmin().ListAccount(ctx, &converted.Params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, true, map[string]any{"items": page.Items, "nextCursor": page.NextCursor})
				},
			},
			{
				Name:                      "create",
				DisableSliceFlagSeparator: true,
				Usage:                     "Create a workspace",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "metadata", Usage: "YAML/JSON document (literal, @path, or - for stdin).", TakesFile: true},
					&cli.StringFlag{Name: "name", Usage: "Required. Human-readable name for the resource (e.g., \"Production API Key\", \"Staging Workspace\")."},
					&cli.StringFlag{Name: "external-id", Usage: "External ID for the resource (e.g., a workflow ID from an external system)."},
					&cli.StringSliceFlag{Name: "label", Usage: "Key-value pairs for categorization and filtering. Values are 0-63 alphanumeric characters with \"-\", \"_\", or \".\" allowed between; keys follow the same shape and…. KEY=VALUE (repeatable; or a document)."},
					&cli.StringFlag{Name: "spec", Usage: "YAML/JSON document (literal, @path, or - for stdin).", TakesFile: true},
					&cli.StringFlag{Name: "description", Usage: ""},
					&cli.StringFlag{Name: "file", Aliases: []string{"f"}, TakesFile: true, Usage: "Whole request body from a YAML/JSON file (or - for stdin); other flags override its values"},
					&cli.BoolFlag{Name: "dry-run", Usage: "Print the assembled request body (YAML; JSON with --display json) and exit without calling the API"},
					&cli.BoolFlag{Name: "strict", Usage: "Reject fields the request does not accept in --file and document inputs instead of dropping them with a warning"},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}}
					_stdinInputs := []string{cmd.String("file"), cmd.String("metadata"), cmd.String("name"), cmd.String("external-id"), cmd.String("spec"), cmd.String("description")}
					_stdinInputs = append(_stdinInputs, cmd.StringSlice("label")...)
					if err := stdinBudget(_stdinInputs); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					var converted commands.WorkspaceAdminCreateConversion
					if err := commands.ConvertWorkspaceAdminCreate(cmd, &converted); err != nil {
						return err
					}
					if cmd.Bool("dry-run") {
						return printDocument(_display, converted.Body)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.WorkspaceAdmin().Create(ctx, &converted.Params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "retrieve",
				DisableSliceFlagSeparator: true,
				Usage:                     "Get a workspace by ID",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID to retrieve (path)."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}}
					var converted commands.WorkspaceAdminRetrieveConversion
					if err := commands.ConvertWorkspaceAdminRetrieve(cmd, &converted); err != nil {
						return err
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.WorkspaceAdmin().Retrieve(ctx, &converted.Params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "archive",
				DisableSliceFlagSeparator: true,
				Usage:                     "Archive a workspace",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID to archive (path)."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					if _display != "json" && _display != "yaml" {
						return cli.Exit("this command has no displayable response; use --display json", 2)
					}
					var converted commands.WorkspaceAdminArchiveConversion
					if err := commands.ConvertWorkspaceAdminArchive(cmd, &converted); err != nil {
						return err
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					return client.WorkspaceAdmin().Archive(ctx, &converted.Params)
				},
			},
			{
				Name:                      "update",
				DisableSliceFlagSeparator: true,
				Usage:                     "Update a workspace",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID to update (path)."},
					&cli.StringFlag{Name: "metadata", Usage: "YAML/JSON document (literal, @path, or - for stdin).", TakesFile: true},
					&cli.StringFlag{Name: "name", Usage: "Human-readable name for the resource (e.g., \"Production API Key\", \"Staging Workspace\")."},
					&cli.StringFlag{Name: "external-id", Usage: "External ID for the resource (e.g., a workflow ID from an external system)."},
					&cli.StringSliceFlag{Name: "label", Usage: "Key-value pairs for categorization and filtering. Values are 0-63 alphanumeric characters with \"-\", \"_\", or \".\" allowed between; keys follow the same shape and…. KEY=VALUE (repeatable; or a document)."},
					&cli.StringFlag{Name: "spec", Usage: "YAML/JSON document (literal, @path, or - for stdin).", TakesFile: true},
					&cli.StringFlag{Name: "description", Usage: ""},
					&cli.StringFlag{Name: "update-mask", Usage: "Fields to update."},
					&cli.StringFlag{Name: "file", Aliases: []string{"f"}, TakesFile: true, Usage: "Whole request body from a YAML/JSON file (or - for stdin); other flags override its values"},
					&cli.BoolFlag{Name: "dry-run", Usage: "Print the assembled request body (YAML; JSON with --display json) and exit without calling the API"},
					&cli.BoolFlag{Name: "strict", Usage: "Reject fields the request does not accept in --file and document inputs instead of dropping them with a warning"},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}}
					_stdinInputs := []string{cmd.String("file"), cmd.String("metadata"), cmd.String("name"), cmd.String("external-id"), cmd.String("spec"), cmd.String("description"), cmd.String("update-mask")}
					_stdinInputs = append(_stdinInputs, cmd.StringSlice("label")...)
					if err := stdinBudget(_stdinInputs); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					var converted commands.WorkspaceAdminUpdateConversion
					if err := commands.ConvertWorkspaceAdminUpdate(cmd, &converted); err != nil {
						return err
					}
					if cmd.Bool("dry-run") {
						return printDocument(_display, converted.Body)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.WorkspaceAdmin().Update(ctx, &converted.Params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "list-members",
				DisableSliceFlagSeparator: true,
				Usage:                     "List workspace members",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "The workspace whose members will be listed (path)."},
					&cli.Int32Flag{Name: "limit", Usage: "Maximum number of results to return"},
					&cli.StringFlag{Name: "cursor", Usage: "Pagination cursor from previous response"},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "PROFILE", path: []string{"profileId"}}, {header: "ACTOR", path: []string{"actorId"}}}
					var converted commands.WorkspaceAdminListMembersConversion
					if err := commands.ConvertWorkspaceAdminListMembers(cmd, &converted); err != nil {
						return err
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					page, err := client.WorkspaceAdmin().ListMembers(ctx, &converted.Params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, true, map[string]any{"items": page.Items, "nextCursor": page.NextCursor})
				},
			},
			{
				Name:                      "add-member",
				DisableSliceFlagSeparator: true,
				Usage:                     "Add a member to a workspace",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "The workspace to add the member to (path)."},
					&cli.StringFlag{Name: "profile-id", Usage: "An existing account profile to add. Mutually exclusive with email."},
					&cli.StringFlag{Name: "email", Usage: "Email address to add (resolve-or-invite). Mutually exclusive with profile_id."},
					&cli.StringFlag{Name: "file", Aliases: []string{"f"}, TakesFile: true, Usage: "Whole request body from a YAML/JSON file (or - for stdin); other flags override its values"},
					&cli.BoolFlag{Name: "dry-run", Usage: "Print the assembled request body (YAML; JSON with --display json) and exit without calling the API"},
					&cli.BoolFlag{Name: "strict", Usage: "Reject fields the request does not accept in --file and document inputs instead of dropping them with a warning"},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					if _display != "json" && _display != "yaml" && !cmd.Bool("dry-run") {
						return cli.Exit("no display columns apply to this command; use --display json or yaml", 2)
					}
					_columns := []displayColumn(nil)
					_stdinInputs := []string{cmd.String("file"), cmd.String("profile-id"), cmd.String("email")}
					if err := stdinBudget(_stdinInputs); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					var converted commands.WorkspaceAdminAddMemberConversion
					if err := commands.ConvertWorkspaceAdminAddMember(cmd, &converted); err != nil {
						return err
					}
					if cmd.Bool("dry-run") {
						return printDocument(_display, converted.Body)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.WorkspaceAdmin().AddMember(ctx, &converted.Params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "remove-member",
				DisableSliceFlagSeparator: true,
				Usage:                     "Remove a member from a workspace",
				ArgsUsage:                 "<profile-id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "The workspace to remove the member from (path)."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<profile-id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<profile-id> must not be empty", 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					if _display != "json" && _display != "yaml" {
						return cli.Exit("this command has no displayable response; use --display json", 2)
					}
					pos0 := cmd.Args().Get(0) // profile-id
					var converted commands.WorkspaceAdminRemoveMemberConversion
					if err := commands.ConvertWorkspaceAdminRemoveMember(cmd, &converted); err != nil {
						return err
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					return client.WorkspaceAdmin().RemoveMember(ctx, pos0, &converted.Params)
				},
			},
		},
	}
}
