// Code generated by redwood. DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"strings"

	"github.com/urfave/cli/v3"

	commands "go.cadenya.com/cadenya-cli/internal/commands"
)

func widgetsCommand() *cli.Command {
	return &cli.Command{
		Name:                      "widgets",
		DisableSliceFlagSeparator: true,
		Commands: []*cli.Command{
			{
				Name:                      "list",
				DisableSliceFlagSeparator: true,
				Usage:                     "List widgets",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
					&cli.Int32Flag{Name: "limit", Usage: "Maximum number of results to return."},
					&cli.StringFlag{Name: "cursor", Usage: "Pagination cursor from previous response."},
					&cli.StringFlag{Name: "agent-id", Usage: "Filter to widgets bound to a specific agent. Accepts the canonical `agent_…` form or the `external_id:<value>` form."},
					&cli.StringFlag{Name: "labels", Usage: "Filters by metadata labels. Comma-separated key=value pairs, e.g. \"env=prod,team=ai\". A resource matches only if every pair matches exactly (AND semantics)."},
					&cli.StringFlag{Name: "sort-order", Usage: "Sort order for results (asc or desc by creation time)."},
					&cli.BoolFlag{Name: "include-info", Usage: "When true, the `info` field on each returned widget is populated. Requests with this flag count more against your rate limit."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}, {header: "AGENT", path: []string{"spec", "agentId"}}}
					var converted commands.WidgetsListConversion
					if err := commands.ConvertWidgetsList(cmd, &converted); err != nil {
						return err
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					page, err := client.Widgets().List(ctx, &converted.Params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, true, map[string]any{"items": page.Items, "nextCursor": page.NextCursor})
				},
			},
			{
				Name:                      "create",
				DisableSliceFlagSeparator: true,
				Usage:                     "Create a new widget",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
					&cli.StringFlag{Name: "metadata", Usage: "YAML/JSON document (literal, @path, or - for stdin).", TakesFile: true},
					&cli.StringFlag{Name: "name", Usage: "Required. Human-readable name for the resource (e.g., \"Customer Support Agent\", \"Email Tool\")."},
					&cli.StringFlag{Name: "external-id", Usage: "External ID for the resource (e.g., a workflow ID from an external system)."},
					&cli.StringSliceFlag{Name: "label", Usage: "Key-value pairs for categorization and filtering. Values are 0-63 alphanumeric characters with \"-\", \"_\", or \".\" allowed between; keys follow the same shape and…. KEY=VALUE (repeatable; or a document)."},
					&cli.StringFlag{Name: "spec", Usage: "YAML/JSON document (literal, @path, or - for stdin).", TakesFile: true},
					&cli.StringFlag{Name: "agent-id", Usage: "Required. Agent this widget is bound to. Accepts the canonical `agent_…` form or the `external_id:<value>` form. Sessions copy the agent at mint: re-pointing a…."},
					&cli.StringFlag{Name: "variation-id", Usage: "Optional explicit variation pin. Must belong to the widget's agent. When set, every objective created through the widget runs this variation — bypassing the…."},
					&cli.StringSliceFlag{Name: "origin-allowlist", Usage: "Web origins allowed to embed and use this widget, enforced at the edge on every browser request. Exact origins only (scheme + host + optional port), no paths,…. Repeatable."},
					&cli.StringFlag{Name: "file", Aliases: []string{"f"}, TakesFile: true, Usage: "Whole request body from a YAML/JSON file (or - for stdin); other flags override its values"},
					&cli.BoolFlag{Name: "dry-run", Usage: "Print the assembled request body (YAML; JSON with --display json) and exit without calling the API"},
					&cli.BoolFlag{Name: "strict", Usage: "Reject fields the request does not accept in --file and document inputs instead of dropping them with a warning"},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					_stdinInputs := []string{cmd.String("file"), cmd.String("metadata"), cmd.String("name"), cmd.String("external-id"), cmd.String("spec"), cmd.String("agent-id"), cmd.String("variation-id")}
					_stdinInputs = append(_stdinInputs, cmd.StringSlice("label")...)
					if err := stdinBudget(_stdinInputs); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					var converted commands.WidgetsCreateConversion
					if err := commands.ConvertWidgetsCreate(cmd, &converted); err != nil {
						return err
					}
					if cmd.Bool("dry-run") {
						return printDocument(_display, converted.Body)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.Widgets().Create(ctx, &converted.Params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "retrieve",
				DisableSliceFlagSeparator: true,
				Usage:                     "Get a widget by ID",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					pos0 := cmd.Args().Get(0) // id
					var converted commands.WidgetsRetrieveConversion
					if err := commands.ConvertWidgetsRetrieve(cmd, &converted); err != nil {
						return err
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.Widgets().Retrieve(ctx, pos0, &converted.Params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "delete",
				DisableSliceFlagSeparator: true,
				Usage:                     "Delete a widget",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					if _display != "json" && _display != "yaml" {
						return cli.Exit("this command has no displayable response; use --display json", 2)
					}
					pos0 := cmd.Args().Get(0) // id
					var converted commands.WidgetsDeleteConversion
					if err := commands.ConvertWidgetsDelete(cmd, &converted); err != nil {
						return err
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					return client.Widgets().Delete(ctx, pos0, &converted.Params)
				},
			},
			{
				Name:                      "update",
				DisableSliceFlagSeparator: true,
				Usage:                     "Update a widget",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
					&cli.StringFlag{Name: "metadata", Usage: "YAML/JSON document (literal, @path, or - for stdin).", TakesFile: true},
					&cli.StringFlag{Name: "name", Usage: "Human-readable name for the resource (e.g., \"Customer Support Agent\", \"Email Tool\")."},
					&cli.StringFlag{Name: "external-id", Usage: "External ID for the resource (e.g., a workflow ID from an external system)."},
					&cli.StringSliceFlag{Name: "label", Usage: "Key-value pairs for categorization and filtering. Values are 0-63 alphanumeric characters with \"-\", \"_\", or \".\" allowed between; keys follow the same shape and…. KEY=VALUE (repeatable; or a document)."},
					&cli.StringFlag{Name: "spec", Usage: "YAML/JSON document (literal, @path, or - for stdin).", TakesFile: true},
					&cli.StringFlag{Name: "agent-id", Usage: "Agent this widget is bound to. Accepts the canonical `agent_…` form or the `external_id:<value>` form. Sessions copy the agent at mint: re-pointing a…."},
					&cli.StringFlag{Name: "variation-id", Usage: "Optional explicit variation pin. Must belong to the widget's agent. When set, every objective created through the widget runs this variation — bypassing the…."},
					&cli.StringSliceFlag{Name: "origin-allowlist", Usage: "Web origins allowed to embed and use this widget, enforced at the edge on every browser request. Exact origins only (scheme + host + optional port), no paths,…. Repeatable."},
					&cli.StringFlag{Name: "update-mask", Usage: "Fields to update."},
					&cli.StringFlag{Name: "file", Aliases: []string{"f"}, TakesFile: true, Usage: "Whole request body from a YAML/JSON file (or - for stdin); other flags override its values"},
					&cli.BoolFlag{Name: "dry-run", Usage: "Print the assembled request body (YAML; JSON with --display json) and exit without calling the API"},
					&cli.BoolFlag{Name: "strict", Usage: "Reject fields the request does not accept in --file and document inputs instead of dropping them with a warning"},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					_stdinInputs := []string{cmd.String("file"), cmd.String("metadata"), cmd.String("name"), cmd.String("external-id"), cmd.String("spec"), cmd.String("agent-id"), cmd.String("variation-id"), cmd.String("update-mask")}
					_stdinInputs = append(_stdinInputs, cmd.StringSlice("label")...)
					if err := stdinBudget(_stdinInputs); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					pos0 := cmd.Args().Get(0) // id
					var converted commands.WidgetsUpdateConversion
					if err := commands.ConvertWidgetsUpdate(cmd, &converted); err != nil {
						return err
					}
					if cmd.Bool("dry-run") {
						return printDocument(_display, converted.Body)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.Widgets().Update(ctx, pos0, &converted.Params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "archive",
				DisableSliceFlagSeparator: true,
				Usage:                     "Archive a widget",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					pos0 := cmd.Args().Get(0) // id
					var converted commands.WidgetsArchiveConversion
					if err := commands.ConvertWidgetsArchive(cmd, &converted); err != nil {
						return err
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.Widgets().Archive(ctx, pos0, &converted.Params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "unarchive",
				DisableSliceFlagSeparator: true,
				Usage:                     "Unarchive a widget",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					pos0 := cmd.Args().Get(0) // id
					var converted commands.WidgetsUnarchiveConversion
					if err := commands.ConvertWidgetsUnarchive(cmd, &converted); err != nil {
						return err
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.Widgets().Unarchive(ctx, pos0, &converted.Params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
		},
	}
}
