// Code generated by redwood. DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"strings"

	"github.com/urfave/cli/v3"

	sdk "go.cadenya.com/cadenya-go"
)

func widgetsCommand() *cli.Command {
	return &cli.Command{
		Name:                      "widgets",
		DisableSliceFlagSeparator: true,
		Commands: []*cli.Command{
			{
				Name:                      "list",
				DisableSliceFlagSeparator: true,
				Usage:                     "List widgets",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
					&cli.IntFlag{Name: "limit", Usage: "Maximum number of results to return."},
					&cli.StringFlag{Name: "cursor", Usage: "Pagination cursor from previous response."},
					&cli.StringFlag{Name: "agent-id", Usage: "Filter to widgets bound to a specific agent. Accepts the canonical `agent_…` form or the `external_id:<value>` form."},
					&cli.StringFlag{Name: "labels", Usage: "Filters by metadata labels. Comma-separated key=value pairs, e.g. \"env=prod,team=ai\". A resource matches only if every pair matches exactly (AND semantics)."},
					&cli.StringFlag{Name: "sort-order", Usage: "Sort order for results (asc or desc by creation time)."},
					&cli.BoolFlag{Name: "include-info", Usage: "When true, the `info` field on each returned widget is populated. Requests with this flag count more against your rate limit."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}, {header: "AGENT", path: []string{"spec", "agentId"}}}
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					if cmd.IsSet("limit") {
						values["limit"] = cmd.Int("limit")
					}
					if cmd.IsSet("cursor") {
						values["cursor"] = cmd.String("cursor")
					}
					if cmd.IsSet("agent-id") {
						values["agentId"] = cmd.String("agent-id")
					}
					if cmd.IsSet("labels") {
						values["labels"] = cmd.String("labels")
					}
					if cmd.IsSet("sort-order") {
						values["sortOrder"] = cmd.String("sort-order")
					}
					if cmd.IsSet("include-info") {
						values["includeInfo"] = cmd.Bool("include-info")
					}
					var params sdk.WidgetListParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					page, err := client.Widgets().List(ctx, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, true, map[string]any{"items": page.Items, "nextCursor": page.NextCursor})
				},
			},
			{
				Name:                      "create",
				DisableSliceFlagSeparator: true,
				Usage:                     "Create a new widget",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
					&cli.StringFlag{Name: "metadata", Usage: "Required. JSON document (literal, @file, or - for stdin)"},
					&cli.StringFlag{Name: "spec", Usage: "Required. JSON document (literal, @file, or - for stdin)"},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					_missing := []string{}
					if !cmd.IsSet("metadata") {
						_missing = append(_missing, "--metadata")
					}
					if !cmd.IsSet("spec") {
						_missing = append(_missing, "--spec")
					}
					if len(_missing) > 0 {
						return cli.Exit("required flag(s) not set: "+strings.Join(_missing, ", "), 2)
					}
					_stdinInputs := []string{cmd.String("metadata"), cmd.String("spec")}
					if err := stdinBudget(_stdinInputs); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					if cmd.IsSet("metadata") {
						doc, err := jsonArg("metadata", cmd.String("metadata"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						values["metadata"] = doc
					}
					if cmd.IsSet("spec") {
						doc, err := jsonArg("spec", cmd.String("spec"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						values["spec"] = doc
					}
					var params sdk.WidgetCreateParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.Widgets().Create(ctx, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "retrieve",
				DisableSliceFlagSeparator: true,
				Usage:                     "Get a widget by ID",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					var params sdk.WidgetRetrieveParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.Widgets().Retrieve(ctx, pos0, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "delete",
				DisableSliceFlagSeparator: true,
				Usage:                     "Delete a widget",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					if _display != "json" {
						return cli.Exit("this command has no displayable response; use --display json", 2)
					}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					var params sdk.WidgetDeleteParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					return client.Widgets().Delete(ctx, pos0, &params)
				},
			},
			{
				Name:                      "update",
				DisableSliceFlagSeparator: true,
				Usage:                     "Update a widget",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
					&cli.StringFlag{Name: "metadata", Usage: "JSON document (literal, @file, or - for stdin)"},
					&cli.StringFlag{Name: "spec", Usage: "JSON document (literal, @file, or - for stdin)"},
					&cli.StringFlag{Name: "update-mask", Usage: "Fields to update."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					_stdinInputs := []string{cmd.String("metadata"), cmd.String("spec")}
					if err := stdinBudget(_stdinInputs); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					if cmd.IsSet("metadata") {
						doc, err := jsonArg("metadata", cmd.String("metadata"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						values["metadata"] = doc
					}
					if cmd.IsSet("spec") {
						doc, err := jsonArg("spec", cmd.String("spec"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						values["spec"] = doc
					}
					if cmd.IsSet("update-mask") {
						values["updateMask"] = cmd.String("update-mask")
					}
					var params sdk.WidgetUpdateParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.Widgets().Update(ctx, pos0, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "archive",
				DisableSliceFlagSeparator: true,
				Usage:                     "Archive a widget",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					var params sdk.WidgetArchiveParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.Widgets().Archive(ctx, pos0, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "unarchive",
				DisableSliceFlagSeparator: true,
				Usage:                     "Unarchive a widget",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					var params sdk.WidgetUnarchiveParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.Widgets().Unarchive(ctx, pos0, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
		},
	}
}
