// Code generated by redwood. DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"strings"

	"github.com/urfave/cli/v3"

	sdk "go.cadenya.com/cadenya-go"
)

const bodySchemaWorkspaceSecretsCreate = "{\"$defs\":{\"CreateResourceMetadata\":{\"properties\":{\"externalId\":{\"description\":\"External ID for the resource (e.g., a workflow ID from an external system)\",\"type\":\"string\"},\"labels\":{\"additionalProperties\":{\"type\":\"string\"},\"description\":\"Key-value pairs for categorization and filtering. Values are 0-63\\n alphanumeric characters with \\\"-\\\", \\\"_\\\", or \\\".\\\" allowed between; keys\\n follow the same shape and additionally accept an optional DNS-subdomain\\n prefix (e.g. \\\"cadenya.com/\\\") of at most 253 characters.\\n Examples: {\\\"environment\\\": \\\"production\\\", \\\"team\\\": \\\"platform\\\", \\\"version\\\": \\\"v2\\\"}\",\"type\":\"object\"},\"name\":{\"description\":\"Human-readable name for the resource (e.g., \\\"Customer Support Agent\\\", \\\"Email Tool\\\")\",\"type\":\"string\"}},\"required\":[\"name\"],\"type\":\"object\"},\"WorkspaceSecretSpec\":{\"properties\":{\"value\":{\"type\":\"string\"}},\"type\":\"object\"}},\"properties\":{\"metadata\":{\"$ref\":\"CreateResourceMetadata\"},\"spec\":{\"$ref\":\"WorkspaceSecretSpec\"}},\"required\":[\"metadata\",\"spec\"],\"type\":\"object\"}"

const bodySchemaWorkspaceSecretsUpdate = "{\"$defs\":{\"UpdateResourceMetadata\":{\"properties\":{\"externalId\":{\"description\":\"External ID for the resource (e.g., a workflow ID from an external system)\",\"type\":\"string\"},\"labels\":{\"additionalProperties\":{\"type\":\"string\"},\"description\":\"Key-value pairs for categorization and filtering. Values are 0-63\\n alphanumeric characters with \\\"-\\\", \\\"_\\\", or \\\".\\\" allowed between; keys\\n follow the same shape and additionally accept an optional DNS-subdomain\\n prefix (e.g. \\\"cadenya.com/\\\") of at most 253 characters.\\n Examples: {\\\"environment\\\": \\\"production\\\", \\\"team\\\": \\\"platform\\\", \\\"version\\\": \\\"v2\\\"}\",\"type\":\"object\"},\"name\":{\"description\":\"Human-readable name for the resource (e.g., \\\"Customer Support Agent\\\", \\\"Email Tool\\\")\",\"type\":\"string\"}},\"required\":[\"name\"],\"type\":\"object\"},\"WorkspaceSecretSpec\":{\"properties\":{\"value\":{\"type\":\"string\"}},\"type\":\"object\"}},\"properties\":{\"metadata\":{\"$ref\":\"UpdateResourceMetadata\"},\"spec\":{\"$ref\":\"WorkspaceSecretSpec\"},\"updateMask\":{\"type\":\"string\"}},\"type\":\"object\"}"

func workspaceSecretsCommand() *cli.Command {
	return &cli.Command{
		Name:                      "workspace-secrets",
		DisableSliceFlagSeparator: true,
		Commands: []*cli.Command{
			{
				Name:                      "list",
				DisableSliceFlagSeparator: true,
				Usage:                     "List workspace secrets",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "The workspace whose secrets will be listed."},
					&cli.IntFlag{Name: "limit", Usage: "Maximum number of results to return"},
					&cli.StringFlag{Name: "cursor", Usage: "Pagination cursor from previous response"},
					&cli.StringFlag{Name: "prefix", Usage: "Filter expression (query param: prefix)"},
					&cli.StringFlag{Name: "query", Usage: "Free-form search query"},
					&cli.StringFlag{Name: "labels", Usage: "Filters by metadata labels. Comma-separated key=value pairs, e.g. \"env=prod,team=ai\". A resource matches only if every pair matches exactly (AND semantics)."},
					&cli.StringFlag{Name: "sort-order", Usage: "Sort order for results (asc or desc by creation time)"},
					&cli.BoolFlag{Name: "include-info", Usage: "When set to true you may use more of your alloted API rate-limit"},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}}
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					if cmd.IsSet("limit") {
						values["limit"] = cmd.Int("limit")
					}
					if cmd.IsSet("cursor") {
						values["cursor"] = cmd.String("cursor")
					}
					if cmd.IsSet("prefix") {
						values["prefix"] = cmd.String("prefix")
					}
					if cmd.IsSet("query") {
						values["query"] = cmd.String("query")
					}
					if cmd.IsSet("labels") {
						values["labels"] = cmd.String("labels")
					}
					if cmd.IsSet("sort-order") {
						values["sortOrder"] = cmd.String("sort-order")
					}
					if cmd.IsSet("include-info") {
						values["includeInfo"] = cmd.Bool("include-info")
					}
					var params sdk.WorkspaceSecretListParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					page, err := client.WorkspaceSecrets().List(ctx, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, true, map[string]any{"items": page.Items, "nextCursor": page.NextCursor})
				},
			},
			{
				Name:                      "create",
				DisableSliceFlagSeparator: true,
				Usage:                     "Create a new workspace secret",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "The workspace that will own this secret."},
					&cli.StringFlag{Name: "metadata", Usage: "YAML/JSON document (literal, @path, or - for stdin).", TakesFile: true},
					&cli.StringFlag{Name: "name", Usage: "Required. Human-readable name for the resource (e.g., \"Customer Support Agent\", \"Email Tool\")."},
					&cli.StringFlag{Name: "external-id", Usage: "External ID for the resource (e.g., a workflow ID from an external system)."},
					&cli.StringSliceFlag{Name: "label", Usage: "Key-value pairs for categorization and filtering. Values are 0-63 alphanumeric characters with \"-\", \"_\", or \".\" allowed between; keys follow the same shape and…. KEY=VALUE (repeatable; or a document)."},
					&cli.StringFlag{Name: "spec", Usage: "YAML/JSON document (literal, @path, or - for stdin).", TakesFile: true},
					&cli.StringFlag{Name: "value", Usage: ""},
					&cli.StringFlag{Name: "file", Aliases: []string{"f"}, TakesFile: true, Usage: "Whole request body from a YAML/JSON file (or - for stdin); other flags override its values"},
					&cli.BoolFlag{Name: "dry-run", Usage: "Print the assembled request body (YAML; JSON with --display json) and exit without calling the API"},
					&cli.BoolFlag{Name: "strict", Usage: "Reject fields the request does not accept in --file and document inputs instead of dropping them with a warning"},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}}
					_stdinInputs := []string{cmd.String("file"), cmd.String("metadata"), cmd.String("name"), cmd.String("external-id"), cmd.String("spec"), cmd.String("value")}
					_stdinInputs = append(_stdinInputs, cmd.StringSlice("label")...)
					if err := stdinBudget(_stdinInputs); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					_schema := parseBodySchema(bodySchemaWorkspaceSecretsCreate)
					_body := newBodyBuilder()
					_strict := cmd.Bool("strict")
					var _rawBody any
					if cmd.IsSet("file") {
						if err := _body.applyFile("file", cmd.String("file"), _schema, _strict); err != nil {
							return cli.Exit(err.Error(), 2)
						}
					}
					if cmd.IsSet("metadata") {
						if err := _body.applyDoc("metadata", []string{"metadata"}, cmd.String("metadata"), _schema, _strict); err != nil {
							return cli.Exit(err.Error(), 2)
						}
					}
					if cmd.IsSet("spec") {
						if err := _body.applyDoc("spec", []string{"spec"}, cmd.String("spec"), _schema, _strict); err != nil {
							return cli.Exit(err.Error(), 2)
						}
					}
					if cmd.IsSet("name") {
						_v, err := stringArg("name", cmd.String("name"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						if err := _body.set("name", []string{"metadata", "name"}, _v); err != nil {
							return cli.Exit(err.Error(), 2)
						}
					}
					if cmd.IsSet("external-id") {
						_v, err := stringArg("external-id", cmd.String("external-id"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						if err := _body.set("external-id", []string{"metadata", "externalId"}, _v); err != nil {
							return cli.Exit(err.Error(), 2)
						}
					}
					if cmd.IsSet("label") {
						if err := _body.applyEntries("label", []string{"metadata", "labels"}, cmd.StringSlice("label"), scalarString, nil); err != nil {
							return cli.Exit(err.Error(), 2)
						}
					}
					if cmd.IsSet("value") {
						_v, err := stringArg("value", cmd.String("value"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						if err := _body.set("value", []string{"spec", "value"}, _v); err != nil {
							return cli.Exit(err.Error(), 2)
						}
					}
					if err := _body.finish(_schema, map[string]string{"metadata": "--metadata", "metadata.name": "--name", "metadata.externalId": "--external-id", "metadata.labels": "--label", "spec": "--spec", "spec.value": "--value"}); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					if cmd.Bool("dry-run") {
						if _rawBody != nil {
							return printDocument(_display, _rawBody)
						}
						return printDocument(_display, _body.body)
					}
					_ = _rawBody
					for _k, _v := range _body.body {
						values[_k] = _v
					}
					var params sdk.WorkspaceSecretCreateParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.WorkspaceSecrets().Create(ctx, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "retrieve",
				DisableSliceFlagSeparator: true,
				Usage:                     "Get a workspace secret by ID",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "The workspace the secret belongs to."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					var params sdk.WorkspaceSecretRetrieveParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.WorkspaceSecrets().Retrieve(ctx, pos0, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "delete",
				DisableSliceFlagSeparator: true,
				Usage:                     "Delete a workspace secret",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "The workspace the secret belongs to."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					if _display != "json" && _display != "yaml" {
						return cli.Exit("this command has no displayable response; use --display json", 2)
					}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					var params sdk.WorkspaceSecretDeleteParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					return client.WorkspaceSecrets().Delete(ctx, pos0, &params)
				},
			},
			{
				Name:                      "update",
				DisableSliceFlagSeparator: true,
				Usage:                     "Update a workspace secret",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, yaml, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "The workspace the secret belongs to."},
					&cli.StringFlag{Name: "metadata", Usage: "YAML/JSON document (literal, @path, or - for stdin).", TakesFile: true},
					&cli.StringFlag{Name: "name", Usage: "Human-readable name for the resource (e.g., \"Customer Support Agent\", \"Email Tool\")."},
					&cli.StringFlag{Name: "external-id", Usage: "External ID for the resource (e.g., a workflow ID from an external system)."},
					&cli.StringSliceFlag{Name: "label", Usage: "Key-value pairs for categorization and filtering. Values are 0-63 alphanumeric characters with \"-\", \"_\", or \".\" allowed between; keys follow the same shape and…. KEY=VALUE (repeatable; or a document)."},
					&cli.StringFlag{Name: "spec", Usage: "YAML/JSON document (literal, @path, or - for stdin).", TakesFile: true},
					&cli.StringFlag{Name: "value", Usage: ""},
					&cli.StringFlag{Name: "update-mask", Usage: "Fields to update."},
					&cli.StringFlag{Name: "file", Aliases: []string{"f"}, TakesFile: true, Usage: "Whole request body from a YAML/JSON file (or - for stdin); other flags override its values"},
					&cli.BoolFlag{Name: "dry-run", Usage: "Print the assembled request body (YAML; JSON with --display json) and exit without calling the API"},
					&cli.BoolFlag{Name: "strict", Usage: "Reject fields the request does not accept in --file and document inputs instead of dropping them with a warning"},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "table")
					if !isOneOf(_display, []string{"json", "yaml", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, yaml, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "EXTERNAL ID", path: []string{"metadata", "externalId"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}}
					_stdinInputs := []string{cmd.String("file"), cmd.String("metadata"), cmd.String("name"), cmd.String("external-id"), cmd.String("spec"), cmd.String("value"), cmd.String("update-mask")}
					_stdinInputs = append(_stdinInputs, cmd.StringSlice("label")...)
					if err := stdinBudget(_stdinInputs); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					_schema := parseBodySchema(bodySchemaWorkspaceSecretsUpdate)
					_body := newBodyBuilder()
					_strict := cmd.Bool("strict")
					var _rawBody any
					if cmd.IsSet("file") {
						if err := _body.applyFile("file", cmd.String("file"), _schema, _strict); err != nil {
							return cli.Exit(err.Error(), 2)
						}
					}
					if cmd.IsSet("metadata") {
						if err := _body.applyDoc("metadata", []string{"metadata"}, cmd.String("metadata"), _schema, _strict); err != nil {
							return cli.Exit(err.Error(), 2)
						}
					}
					if cmd.IsSet("spec") {
						if err := _body.applyDoc("spec", []string{"spec"}, cmd.String("spec"), _schema, _strict); err != nil {
							return cli.Exit(err.Error(), 2)
						}
					}
					if cmd.IsSet("name") {
						_v, err := stringArg("name", cmd.String("name"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						if err := _body.set("name", []string{"metadata", "name"}, _v); err != nil {
							return cli.Exit(err.Error(), 2)
						}
					}
					if cmd.IsSet("external-id") {
						_v, err := stringArg("external-id", cmd.String("external-id"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						if err := _body.set("external-id", []string{"metadata", "externalId"}, _v); err != nil {
							return cli.Exit(err.Error(), 2)
						}
					}
					if cmd.IsSet("label") {
						if err := _body.applyEntries("label", []string{"metadata", "labels"}, cmd.StringSlice("label"), scalarString, nil); err != nil {
							return cli.Exit(err.Error(), 2)
						}
					}
					if cmd.IsSet("value") {
						_v, err := stringArg("value", cmd.String("value"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						if err := _body.set("value", []string{"spec", "value"}, _v); err != nil {
							return cli.Exit(err.Error(), 2)
						}
					}
					if cmd.IsSet("update-mask") {
						_v, err := stringArg("update-mask", cmd.String("update-mask"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						if err := _body.set("update-mask", []string{"updateMask"}, _v); err != nil {
							return cli.Exit(err.Error(), 2)
						}
					}
					if err := _body.finish(_schema, map[string]string{"metadata": "--metadata", "metadata.name": "--name", "metadata.externalId": "--external-id", "metadata.labels": "--label", "spec": "--spec", "spec.value": "--value", "updateMask": "--update-mask"}); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					// A partial update names the paths it changes; a mask supplied
					// by flag or document wins.
					if _, _given := _body.lookup([]string{"updateMask"}); !_given {
						if _mask := _body.updateMask("updateMask"); _mask != "" {
							_ = _body.set("update-mask", []string{"updateMask"}, _mask)
						}
					}
					if cmd.Bool("dry-run") {
						if _rawBody != nil {
							return printDocument(_display, _rawBody)
						}
						return printDocument(_display, _body.body)
					}
					_ = _rawBody
					for _k, _v := range _body.body {
						values[_k] = _v
					}
					var params sdk.WorkspaceSecretUpdateParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.WorkspaceSecrets().Update(ctx, pos0, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
		},
	}
}
