// Code generated by redwood. DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"strings"

	"github.com/urfave/cli/v3"

	sdk "go.cadenya.com/cadenya-go"
)

func aPIKeysCommand() *cli.Command {
	return &cli.Command{
		Name:                      "api-keys",
		DisableSliceFlagSeparator: true,
		Commands: []*cli.Command{
			{
				Name:                      "retrieve-global",
				DisableSliceFlagSeparator: true,
				Usage:                     "Get the global API key",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.APIKeys().RetrieveGlobal(ctx)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "disable-global",
				DisableSliceFlagSeparator: true,
				Usage:                     "Disable the global API key",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.APIKeys().DisableGlobal(ctx)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "enable-global",
				DisableSliceFlagSeparator: true,
				Usage:                     "Enable the global API key",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.APIKeys().EnableGlobal(ctx)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "rotate-global",
				DisableSliceFlagSeparator: true,
				Usage:                     "Rotate the global API key",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.APIKeys().RotateGlobal(ctx)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "list",
				DisableSliceFlagSeparator: true,
				Usage:                     "List API keys",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "The workspace whose API keys will be listed (path)."},
					&cli.IntFlag{Name: "limit", Usage: "Maximum number of results to return."},
					&cli.StringFlag{Name: "cursor", Usage: "Pagination cursor from previous response."},
					&cli.StringFlag{Name: "prefix", Usage: "Filter by ID prefix."},
					&cli.StringFlag{Name: "query", Usage: "Free-form search query."},
					&cli.StringFlag{Name: "labels", Usage: "Filters by metadata labels. Comma-separated key=value pairs, e.g. \"env=prod,team=ai\". A resource matches only if every pair matches exactly (AND semantics)."},
					&cli.StringFlag{Name: "sort-order", Usage: "Sort order for results (asc or desc by creation time)."},
					&cli.BoolFlag{Name: "include-info", Usage: "When true, included info fields are populated. Requests with this flag count more against your rate limit."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					if cmd.IsSet("limit") {
						values["limit"] = cmd.Int("limit")
					}
					if cmd.IsSet("cursor") {
						values["cursor"] = cmd.String("cursor")
					}
					if cmd.IsSet("prefix") {
						values["prefix"] = cmd.String("prefix")
					}
					if cmd.IsSet("query") {
						values["query"] = cmd.String("query")
					}
					if cmd.IsSet("labels") {
						values["labels"] = cmd.String("labels")
					}
					if cmd.IsSet("sort-order") {
						values["sortOrder"] = cmd.String("sort-order")
					}
					if cmd.IsSet("include-info") {
						values["includeInfo"] = cmd.Bool("include-info")
					}
					var params sdk.APIKeyListParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					page, err := client.APIKeys().List(ctx, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, true, map[string]any{"items": page.Items, "nextCursor": page.NextCursor})
				},
			},
			{
				Name:                      "create",
				DisableSliceFlagSeparator: true,
				Usage:                     "Create a new API key",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "The workspace this API key belongs to (path)."},
					&cli.StringFlag{Name: "metadata", Usage: "Required. JSON document (literal, @file, or - for stdin)"},
					&cli.StringFlag{Name: "spec", Usage: "Required. JSON document (literal, @file, or - for stdin)"},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					_missing := []string{}
					if !cmd.IsSet("metadata") {
						_missing = append(_missing, "--metadata")
					}
					if !cmd.IsSet("spec") {
						_missing = append(_missing, "--spec")
					}
					if len(_missing) > 0 {
						return cli.Exit("required flag(s) not set: "+strings.Join(_missing, ", "), 2)
					}
					_stdinInputs := []string{cmd.String("metadata"), cmd.String("spec")}
					if err := stdinBudget(_stdinInputs); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					if cmd.IsSet("metadata") {
						doc, err := jsonArg("metadata", cmd.String("metadata"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						values["metadata"] = doc
					}
					if cmd.IsSet("spec") {
						doc, err := jsonArg("spec", cmd.String("spec"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						values["spec"] = doc
					}
					var params sdk.APIKeyCreateParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.APIKeys().Create(ctx, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "retrieve",
				DisableSliceFlagSeparator: true,
				Usage:                     "Get an API key by ID",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "The workspace the API key belongs to (path)."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					var params sdk.APIKeyRetrieveParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.APIKeys().Retrieve(ctx, pos0, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "delete",
				DisableSliceFlagSeparator: true,
				Usage:                     "Delete an API key",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "The workspace the API key belongs to (path)."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					if _display != "json" {
						return cli.Exit("this command has no displayable response; use --display json", 2)
					}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					var params sdk.APIKeyDeleteParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					return client.APIKeys().Delete(ctx, pos0, &params)
				},
			},
			{
				Name:                      "update",
				DisableSliceFlagSeparator: true,
				Usage:                     "Update an API key",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "The workspace the API key belongs to (path)."},
					&cli.StringFlag{Name: "metadata", Usage: "JSON document (literal, @file, or - for stdin)"},
					&cli.StringFlag{Name: "spec", Usage: "JSON document (literal, @file, or - for stdin)"},
					&cli.StringFlag{Name: "update-mask", Usage: "Fields to update."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					_stdinInputs := []string{cmd.String("metadata"), cmd.String("spec")}
					if err := stdinBudget(_stdinInputs); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					if cmd.IsSet("metadata") {
						doc, err := jsonArg("metadata", cmd.String("metadata"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						values["metadata"] = doc
					}
					if cmd.IsSet("spec") {
						doc, err := jsonArg("spec", cmd.String("spec"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						values["spec"] = doc
					}
					if cmd.IsSet("update-mask") {
						values["updateMask"] = cmd.String("update-mask")
					}
					var params sdk.APIKeyUpdateParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.APIKeys().Update(ctx, pos0, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "disable",
				DisableSliceFlagSeparator: true,
				Usage:                     "Disable an API key",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "The workspace the API key belongs to (path)."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					var params sdk.APIKeyDisableParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.APIKeys().Disable(ctx, pos0, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "enable",
				DisableSliceFlagSeparator: true,
				Usage:                     "Enable an API key",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "The workspace the API key belongs to (path)."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					var params sdk.APIKeyEnableParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.APIKeys().Enable(ctx, pos0, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "rotate",
				DisableSliceFlagSeparator: true,
				Usage:                     "Rotate an API key",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "The workspace the API key belongs to (path)."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "NAME", path: []string{"metadata", "name"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					var params sdk.APIKeyRotateParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.APIKeys().Rotate(ctx, pos0, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
		},
	}
}
