// Code generated by redwood. DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"strings"

	"github.com/urfave/cli/v3"

	sdk "go.cadenya.com/cadenya-go"
)

func widgetSessionsCommand() *cli.Command {
	return &cli.Command{
		Name:                      "widget-sessions",
		DisableSliceFlagSeparator: true,
		Commands: []*cli.Command{
			{
				Name:                      "list",
				DisableSliceFlagSeparator: true,
				Usage:                     "List widget sessions",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
					&cli.IntFlag{Name: "limit", Usage: "Maximum number of results to return."},
					&cli.StringFlag{Name: "cursor", Usage: "Pagination cursor from previous response."},
					&cli.StringFlag{Name: "widget-id", Usage: "Filter to sessions on a specific widget. Accepts the canonical `wgt_…` form or the `external_id:<value>` form."},
					&cli.StringFlag{Name: "tenant-id", Usage: "Filter to sessions belonging to a tenant. Accepts the canonical `tenant_…` form or the `external_id:<value>` form."},
					&cli.StringFlag{Name: "subject-id", Usage: "Filter to sessions asserted for a subject. Accepts the canonical `subj_…` form or the `external_id:<value>` form; the external_id form is scoped within a…"},
					&cli.StringFlag{Name: "state", Usage: "Filter by state. (one of: STATE_UNSPECIFIED, STATE_ACTIVE, STATE_EXPIRED, STATE_REVOKED, STATE_EXHAUSTED)"},
					&cli.StringFlag{Name: "labels", Usage: "Filters by metadata labels. Comma-separated key=value pairs, e.g. \"env=prod,team=ai\". A resource matches only if every pair matches exactly (AND semantics)."},
					&cli.StringFlag{Name: "sort-order", Usage: "Sort order for results (asc or desc by creation time)."},
					&cli.BoolFlag{Name: "include-info", Usage: "When true, the `info` field on each returned session is populated. Requests with this flag count more against your rate limit."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}, {header: "WIDGET", path: []string{"spec", "widgetId"}}}
					if cmd.IsSet("state") && !isOneOf(cmd.String("state"), []string{"STATE_UNSPECIFIED", "STATE_ACTIVE", "STATE_EXPIRED", "STATE_REVOKED", "STATE_EXHAUSTED"}) {
						return cli.Exit(fmt.Sprintf("--state: invalid value %q (valid: STATE_UNSPECIFIED, STATE_ACTIVE, STATE_EXPIRED, STATE_REVOKED, STATE_EXHAUSTED)", cmd.String("state")), 2)
					}
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					if cmd.IsSet("limit") {
						values["limit"] = cmd.Int("limit")
					}
					if cmd.IsSet("cursor") {
						values["cursor"] = cmd.String("cursor")
					}
					if cmd.IsSet("widget-id") {
						values["widgetId"] = cmd.String("widget-id")
					}
					if cmd.IsSet("tenant-id") {
						values["tenantId"] = cmd.String("tenant-id")
					}
					if cmd.IsSet("subject-id") {
						values["subjectId"] = cmd.String("subject-id")
					}
					if cmd.IsSet("state") {
						values["state"] = cmd.String("state")
					}
					if cmd.IsSet("labels") {
						values["labels"] = cmd.String("labels")
					}
					if cmd.IsSet("sort-order") {
						values["sortOrder"] = cmd.String("sort-order")
					}
					if cmd.IsSet("include-info") {
						values["includeInfo"] = cmd.Bool("include-info")
					}
					var params sdk.WidgetSessionListParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					page, err := client.WidgetSessions().List(ctx, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, true, map[string]any{"items": page.Items, "nextCursor": page.NextCursor})
				},
			},
			{
				Name:                      "create",
				DisableSliceFlagSeparator: true,
				Usage:                     "Create a widget session",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
					&cli.StringFlag{Name: "metadata", Usage: "JSON document (literal, @file, or - for stdin)"},
					&cli.StringFlag{Name: "spec", Usage: "Required. JSON document (literal, @file, or - for stdin)"},
					&cli.StringSliceFlag{Name: "secrets", Usage: "Secrets to attach to the session."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					_missing := []string{}
					if !cmd.IsSet("spec") {
						_missing = append(_missing, "--spec")
					}
					if len(_missing) > 0 {
						return cli.Exit("required flag(s) not set: "+strings.Join(_missing, ", "), 2)
					}
					_stdinInputs := []string{cmd.String("metadata"), cmd.String("spec")}
					_stdinInputs = append(_stdinInputs, cmd.StringSlice("secrets")...)
					if err := stdinBudget(_stdinInputs); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					if cmd.IsSet("metadata") {
						doc, err := jsonArg("metadata", cmd.String("metadata"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						values["metadata"] = doc
					}
					if cmd.IsSet("spec") {
						doc, err := jsonArg("spec", cmd.String("spec"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						values["spec"] = doc
					}
					if cmd.IsSet("secrets") {
						items, err := jsonSliceArg("secrets", cmd.StringSlice("secrets"))
						if err != nil {
							return cli.Exit(err.Error(), 2)
						}
						values["secrets"] = items
					}
					var params sdk.WidgetSessionCreateParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.WidgetSessions().Create(ctx, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "delete-tenant",
				DisableSliceFlagSeparator: true,
				Usage:                     "Delete all of a tenant's widget sessions",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
					&cli.StringFlag{Name: "tenant-id", Usage: "Tenant whose sessions to delete. Required — an empty value is rejected rather than matching everything. Accepts the canonical `tenant_…` form or the…"},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 0 {
						return cli.Exit(fmt.Sprintf("unexpected positional arguments: %v", cmd.Args().Slice()), 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					if _display != "json" {
						return cli.Exit("no display columns apply to this command; use --display json", 2)
					}
					_columns := []displayColumn(nil)
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					if cmd.IsSet("tenant-id") {
						values["tenantId"] = cmd.String("tenant-id")
					}
					var params sdk.WidgetSessionDeleteTenantParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.WidgetSessions().DeleteTenant(ctx, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "retrieve",
				DisableSliceFlagSeparator: true,
				Usage:                     "Get a widget session by ID",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					var params sdk.WidgetSessionRetrieveParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.WidgetSessions().Retrieve(ctx, pos0, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
			{
				Name:                      "delete",
				DisableSliceFlagSeparator: true,
				Usage:                     "Delete a widget session",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					if _display != "json" {
						return cli.Exit("this command has no displayable response; use --display json", 2)
					}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					var params sdk.WidgetSessionDeleteParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					return client.WidgetSessions().Delete(ctx, pos0, &params)
				},
			},
			{
				Name:                      "revoke",
				DisableSliceFlagSeparator: true,
				Usage:                     "Revoke a widget session",
				ArgsUsage:                 "<id>",
				Flags: []cli.Flag{
					&cli.StringFlag{Name: "display", Usage: "Output mode (one of: json, table, extended)"},
					&cli.StringFlag{Name: "workspace-id", Usage: "Workspace ID."},
				},
				Action: func(ctx context.Context, cmd *cli.Command) error {
					if cmd.Args().Len() != 1 {
						return cli.Exit(fmt.Sprintf("expected exactly 1 positional argument(s) (<id>), got %d", cmd.Args().Len()), 2)
					}
					if strings.TrimSpace(cmd.Args().Get(0)) == "" {
						return cli.Exit("<id> must not be empty", 2)
					}
					_display := displayMode(cmd, "json")
					if !isOneOf(_display, []string{"json", "table", "extended"}) {
						return cli.Exit(fmt.Sprintf("--display: invalid value %q (valid: json, table, extended)", _display), 2)
					}
					_columns := []displayColumn{{header: "ID", path: []string{"metadata", "id"}}, {header: "CREATED", path: []string{"metadata", "createdAt"}}, {header: "STATE", path: []string{"state"}}}
					pos0 := cmd.Args().Get(0) // id
					values := map[string]any{}
					if cmd.IsSet("workspace-id") {
						values["workspaceId"] = cmd.String("workspace-id")
					}
					var params sdk.WidgetSessionRevokeParams
					if err := decodeParams(values, &params); err != nil {
						return cli.Exit(err.Error(), 2)
					}
					client, err := newClient(cmd)
					if err != nil {
						return err
					}
					out, err := client.WidgetSessions().Revoke(ctx, pos0, &params)
					if err != nil {
						return err
					}
					return renderDisplay(_display, _columns, false, out)
				},
			},
		},
	}
}
