// Code generated by redwood. DO NOT EDIT.
package main

// Persistent client defaults. `cadenya config set workspace-id <id>`
// stores a per-profile default consulted by every command, below the
// command-line flag and the environment variable and above any
// login-derived default: an explicit source always wins.

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	toml "github.com/pelletier/go-toml/v2"
	cli "github.com/urfave/cli/v3"
)

type configKeyInfo struct {
	wire string // wire spelling, accepted as an alias ("workspaceId")
	env  string // environment variable that outranks the stored default
}

// configKeys: canonical (kebab flag) key -> info. Generated from
// [api] client_params.
var configKeys = map[string]configKeyInfo{
	"workspace-id": {wire: "workspaceId", env: "CADENYA_WORKSPACE_ID"},
}

// workspacesConfigKey is the client param the stored login can default
// when exactly one workspace was authorized.
const workspacesConfigKey = "workspace-id"

// canonicalConfigKey accepts the flag spelling ("workspace-id") or the
// wire spelling ("workspaceId").
func canonicalConfigKey(raw string) (string, bool) {
	if _, ok := configKeys[raw]; ok {
		return raw, true
	}
	for flag, info := range configKeys {
		if info.wire == raw {
			return flag, true
		}
	}
	return "", false
}

func configKeyList() []string {
	keys := make([]string, 0, len(configKeys))
	for k := range configKeys {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func unknownConfigKey(raw string) error {
	return cli.Exit(fmt.Sprintf("unknown config key %q (valid: %s)", raw, joinKeys(configKeyList())), 2)
}

func joinKeys(keys []string) string {
	out := ""
	for i, k := range keys {
		if i > 0 {
			out += ", "
		}
		out += k
	}
	return out
}

func configFilePath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolving home directory: %w", err)
	}
	return filepath.Join(home, ".cadenya", "config"), nil
}

// configActiveProfile mirrors the credentials profile so defaults follow
// the same --profile switch (and is self-contained for auth-less builds).
func configActiveProfile(cmd *cli.Command) string {
	if p := cmd.Root().String("profile"); p != "" {
		return p
	}
	return "default"
}

func loadConfigDefaults() (map[string]map[string]string, error) {
	path, err := configFilePath()
	if err != nil {
		return nil, err
	}
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return map[string]map[string]string{}, nil
	}
	if err != nil {
		return nil, err
	}
	profiles := map[string]map[string]string{}
	if err := toml.Unmarshal(data, &profiles); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}
	return profiles, nil
}

func saveConfigDefaults(profiles map[string]map[string]string) error {
	path, err := configFilePath()
	if err != nil {
		return err
	}
	for name, kv := range profiles {
		if len(kv) == 0 {
			delete(profiles, name)
		}
	}
	if len(profiles) == 0 {
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	data, err := toml.Marshal(profiles)
	if err != nil {
		return err
	}
	// Same torn-write discipline as the credentials file: private temp
	// file, then rename over the destination.
	tmp, err := os.CreateTemp(filepath.Dir(path), ".config-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}

// storedConfigValue returns the active profile's stored default for a
// canonical key. Best effort: an unreadable file means "unset", never a
// hard error in the middle of an unrelated command.
func storedConfigValue(cmd *cli.Command, key string) string {
	profiles, err := loadConfigDefaults()
	if err != nil {
		return ""
	}
	return profiles[configActiveProfile(cmd)][key]
}

// effectiveConfigValue resolves a key the way newClient will, returning the
// value and a human-readable source. MIRRORS newClient — keep in sync.
func effectiveConfigValue(cmd *cli.Command, key string) (string, string) {
	info := configKeys[key]
	if cmd.Root().IsSet(key) {
		return cmd.Root().String(key), "--" + key + " flag"
	}
	if v := os.Getenv(info.env); v != "" {
		if storedConfigValue(cmd, key) != "" {
			return v, "$" + info.env + " (environment) — overrides the stored default"
		}
		return v, "$" + info.env + " (environment)"
	}
	if v := storedConfigValue(cmd, key); v != "" {
		return v, fmt.Sprintf("stored default (profile %q)", configActiveProfile(cmd))
	}
	if prof := storedProfile(cmd); prof != nil && key == workspacesConfigKey && len(prof.Workspaces) == 1 {
		return prof.Workspaces[0].ID, "stored login (single authorized workspace)"
	}
	return "", "unset"
}

func configCommand() *cli.Command {
	return &cli.Command{
		Name:  "config",
		Usage: "Persistent per-profile defaults for client-level parameters",
		Commands: []*cli.Command{
			{
				Name:      "set",
				Usage:     "Store a default value for a key",
				ArgsUsage: "<key> <value>",
				Action:    configSet,
			},
			{
				Name:      "get",
				Usage:     "Print a key's stored default (empty if unset)",
				ArgsUsage: "<key>",
				Action:    configGet,
			},
			{
				Name:      "unset",
				Usage:     "Remove a key's stored default",
				ArgsUsage: "<key>",
				Action:    configUnset,
			},
			{
				Name:   "list",
				Usage:  "Show every key's effective value and where it comes from",
				Action: configList,
			},
		},
	}
}

func configSet(_ context.Context, cmd *cli.Command) error {
	if cmd.Args().Len() != 2 {
		return cli.Exit("expected exactly 2 positional argument(s) (<key> <value>)", 2)
	}
	key, ok := canonicalConfigKey(cmd.Args().Get(0))
	if !ok {
		return unknownConfigKey(cmd.Args().Get(0))
	}
	value := cmd.Args().Get(1)
	if value == "" {
		return cli.Exit("value must not be empty; use `config unset` to remove a default", 2)
	}
	profiles, err := loadConfigDefaults()
	if err != nil {
		return err
	}
	profile := configActiveProfile(cmd)
	if profiles[profile] == nil {
		profiles[profile] = map[string]string{}
	}
	profiles[profile][key] = value
	if err := saveConfigDefaults(profiles); err != nil {
		return err
	}
	fmt.Printf("Set %s = %s (profile %q).\n", key, value, profile)
	if info := configKeys[key]; os.Getenv(info.env) != "" {
		fmt.Printf("Note: %s is set in this environment and takes precedence over this default.\n", info.env)
	}
	return nil
}

func configGet(_ context.Context, cmd *cli.Command) error {
	if cmd.Args().Len() != 1 {
		return cli.Exit("expected exactly 1 positional argument(s) (<key>)", 2)
	}
	key, ok := canonicalConfigKey(cmd.Args().Get(0))
	if !ok {
		return unknownConfigKey(cmd.Args().Get(0))
	}
	fmt.Println(storedConfigValue(cmd, key))
	return nil
}

func configUnset(_ context.Context, cmd *cli.Command) error {
	if cmd.Args().Len() != 1 {
		return cli.Exit("expected exactly 1 positional argument(s) (<key>)", 2)
	}
	key, ok := canonicalConfigKey(cmd.Args().Get(0))
	if !ok {
		return unknownConfigKey(cmd.Args().Get(0))
	}
	profiles, err := loadConfigDefaults()
	if err != nil {
		return err
	}
	profile := configActiveProfile(cmd)
	if _, ok := profiles[profile][key]; !ok {
		fmt.Printf("No stored default for %s (profile %q).\n", key, profile)
		return nil
	}
	delete(profiles[profile], key)
	if err := saveConfigDefaults(profiles); err != nil {
		return err
	}
	fmt.Printf("Unset %s (profile %q).\n", key, profile)
	return nil
}

func configList(_ context.Context, cmd *cli.Command) error {
	for _, key := range configKeyList() {
		value, source := effectiveConfigValue(cmd, key)
		if value == "" {
			fmt.Printf("%s: unset\n", key)
			continue
		}
		fmt.Printf("%s: %s (%s)\n", key, value, source)
	}
	return nil
}
