// Code generated by redwood. DO NOT EDIT.
package commands

import (
	cli "github.com/urfave/cli/v3"

	sdk "go.cadenya.com/cadenya-go"
)

// AgentsListFeedbackConversion is the typed request produced from one urfave command.
type AgentsListFeedbackConversion struct {
	Params sdk.AgentListFeedbackParams
	Body   any
}

// ConvertAgentsListFeedback reads urfave values according to Redwood's operation IR.
func ConvertAgentsListFeedback(cmd *cli.Command, out *AgentsListFeedbackConversion) error {
	values := map[string]any{}
	if cmd.IsSet("workspace-id") {
		values["workspaceId"] = cmd.String("workspace-id")
	}
	if cmd.IsSet("limit") {
		values["limit"] = cmd.Int32("limit")
	}
	if cmd.IsSet("cursor") {
		values["cursor"] = cmd.String("cursor")
	}
	if cmd.IsSet("query") {
		values["query"] = cmd.String("query")
	}
	if cmd.IsSet("sentiment") {
		values["sentiment"] = cmd.String("sentiment")
	}
	if cmd.IsSet("agent-variation-id") {
		values["agentVariationId"] = cmd.String("agent-variation-id")
	}
	if cmd.IsSet("created-after") {
		values["createdAfter"] = cmd.String("created-after")
	}
	if cmd.IsSet("created-before") {
		values["createdBefore"] = cmd.String("created-before")
	}
	if cmd.IsSet("labels") {
		values["labels"] = cmd.String("labels")
	}
	if cmd.IsSet("include-info") {
		values["includeInfo"] = cmd.Bool("include-info")
	}
	if err := decodeParams(values, &out.Params); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	return nil
}
