// Code generated by redwood. DO NOT EDIT.
package commands

import (
	cli "github.com/urfave/cli/v3"

	sdk "go.cadenya.com/cadenya-go"
)

// AgentPoolsDeleteConversion is the typed request produced from one urfave command.
type AgentPoolsDeleteConversion struct {
	Params sdk.AgentPoolDeleteParams
	Body   any
}

// ConvertAgentPoolsDelete reads urfave values according to Redwood's operation IR.
func ConvertAgentPoolsDelete(cmd *cli.Command, out *AgentPoolsDeleteConversion) error {
	values := map[string]any{}
	if cmd.IsSet("workspace-id") {
		values["workspaceId"] = cmd.String("workspace-id")
	}
	if err := decodeParams(values, &out.Params); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	return nil
}
