// Code generated by redwood. DO NOT EDIT.
package commands

import (
	cli "github.com/urfave/cli/v3"

	sdk "go.cadenya.com/cadenya-go"
)

const bodySchemaObjectivesCancel = "{\"$defs\":{},\"properties\":{\"reason\":{\"type\":\"string\"}},\"type\":\"object\"}"

// ObjectivesCancelConversion is the typed request produced from one urfave command.
type ObjectivesCancelConversion struct {
	Params sdk.ObjectiveCancelParams
	Body   any
}

// ConvertObjectivesCancel reads urfave values according to Redwood's operation IR.
func ConvertObjectivesCancel(cmd *cli.Command, out *ObjectivesCancelConversion) error {
	values := map[string]any{}
	if cmd.IsSet("workspace-id") {
		values["workspaceId"] = cmd.String("workspace-id")
	}
	_schema := parseBodySchema(bodySchemaObjectivesCancel)
	_body := newBodyBuilder()
	_strict := cmd.Bool("strict")
	var _rawBody any
	if cmd.IsSet("file") {
		if err := _body.applyFile("file", cmd.String("file"), _schema, _strict); err != nil {
			return cli.Exit(err.Error(), 2)
		}
	}
	if cmd.IsSet("reason") {
		_v, err := stringArg("reason", cmd.String("reason"))
		if err != nil {
			return cli.Exit(err.Error(), 2)
		}
		if err := _body.set("reason", []string{"reason"}, _v); err != nil {
			return cli.Exit(err.Error(), 2)
		}
	}
	if err := _body.finish(_schema, map[string]string{"reason": "--reason"}, _strict); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	_ = _rawBody
	for _k, _v := range _body.body {
		values[_k] = _v
	}
	if err := decodeParams(values, &out.Params); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	out.Body = _body.body
	return nil
}
