// Code generated by redwood. DO NOT EDIT.
package commands

import (
	cli "github.com/urfave/cli/v3"

	sdk "go.cadenya.com/cadenya-go"
)

const bodySchemaObjectivesSetToolCallContent = "{\"$defs\":{\"SetToolCallContentRequest_AudioBlock\":{\"properties\":{\"data\":{\"description\":\"Base64-encoded audio bytes.\",\"type\":\"string\"},\"mimeType\":{\"description\":\"IANA media type of the audio, e.g. audio/wav.\",\"type\":\"string\"}},\"required\":[\"data\",\"mimeType\"],\"type\":\"object\"},\"SetToolCallContentRequest_ContentBlock\":{\"discriminator\":{\"propertyName\":\"type\"},\"oneOf\":[{\"$ref\":\"SetToolCallContentRequest_ContentBlock_Text\"},{\"$ref\":\"SetToolCallContentRequest_ContentBlock_Image\"},{\"$ref\":\"SetToolCallContentRequest_ContentBlock_Audio\"}]},\"SetToolCallContentRequest_ContentBlock_Audio\":{\"properties\":{\"audio\":{\"$ref\":\"SetToolCallContentRequest_AudioBlock\"},\"type\":{\"const\":\"audio\"}},\"required\":[\"type\",\"audio\"],\"type\":\"object\"},\"SetToolCallContentRequest_ContentBlock_Image\":{\"properties\":{\"image\":{\"$ref\":\"SetToolCallContentRequest_ImageBlock\"},\"type\":{\"const\":\"image\"}},\"required\":[\"type\",\"image\"],\"type\":\"object\"},\"SetToolCallContentRequest_ContentBlock_Text\":{\"properties\":{\"text\":{\"$ref\":\"SetToolCallContentRequest_TextBlock\"},\"type\":{\"const\":\"text\"}},\"required\":[\"type\",\"text\"],\"type\":\"object\"},\"SetToolCallContentRequest_ImageBlock\":{\"properties\":{\"data\":{\"description\":\"Base64-encoded image bytes.\",\"type\":\"string\"},\"mimeType\":{\"description\":\"IANA media type of the image, e.g. image/png.\",\"type\":\"string\"}},\"required\":[\"data\",\"mimeType\"],\"type\":\"object\"},\"SetToolCallContentRequest_TextBlock\":{\"properties\":{\"text\":{\"type\":\"string\"}},\"required\":[\"text\"],\"type\":\"object\"}},\"properties\":{\"content\":{\"items\":{\"$ref\":\"SetToolCallContentRequest_ContentBlock\"},\"type\":\"array\"}},\"required\":[\"content\"],\"type\":\"object\"}"

// ObjectivesSetToolCallContentConversion is the typed request produced from one urfave command.
type ObjectivesSetToolCallContentConversion struct {
	Params sdk.ObjectiveSetToolCallContentParams
	Body   any
}

// ConvertObjectivesSetToolCallContent reads urfave values according to Redwood's operation IR.
func ConvertObjectivesSetToolCallContent(cmd *cli.Command, out *ObjectivesSetToolCallContentConversion) error {
	values := map[string]any{}
	if cmd.IsSet("workspace-id") {
		values["workspaceId"] = cmd.String("workspace-id")
	}
	_schema := parseBodySchema(bodySchemaObjectivesSetToolCallContent)
	_body := newBodyBuilder()
	_strict := cmd.Bool("strict")
	var _rawBody any
	if cmd.IsSet("file") {
		if err := _body.applyFile("file", cmd.String("file"), _schema, _strict); err != nil {
			return cli.Exit(err.Error(), 2)
		}
	}
	if cmd.IsSet("content") {
		if err := _body.applyDocItems("content", []string{"content"}, cmd.StringSlice("content")); err != nil {
			return cli.Exit(err.Error(), 2)
		}
	}
	if err := _body.finish(_schema, map[string]string{"content": "--content"}, _strict); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	_ = _rawBody
	for _k, _v := range _body.body {
		values[_k] = _v
	}
	if err := decodeParams(values, &out.Params); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	out.Body = _body.body
	return nil
}
