// Code generated by redwood. DO NOT EDIT.
package commands

import (
	cli "github.com/urfave/cli/v3"

	sdk "go.cadenya.com/cadenya-go"
)

// ObjectivesListConversion is the typed request produced from one urfave command.
type ObjectivesListConversion struct {
	Params sdk.ObjectiveListParams
	Body   any
}

// ConvertObjectivesList reads urfave values according to Redwood's operation IR.
func ConvertObjectivesList(cmd *cli.Command, out *ObjectivesListConversion) error {
	values := map[string]any{}
	if cmd.IsSet("workspace-id") {
		values["workspaceId"] = cmd.String("workspace-id")
	}
	if cmd.IsSet("limit") {
		values["limit"] = cmd.Int32("limit")
	}
	if cmd.IsSet("cursor") {
		values["cursor"] = cmd.String("cursor")
	}
	if cmd.IsSet("agent-id") {
		values["agentId"] = cmd.String("agent-id")
	}
	if cmd.IsSet("parent-objective-id") {
		values["parentObjectiveId"] = cmd.String("parent-objective-id")
	}
	if cmd.IsSet("state") {
		values["state"] = cmd.String("state")
	}
	if cmd.IsSet("profile-id") {
		values["profileId"] = cmd.String("profile-id")
	}
	if cmd.IsSet("sort-order") {
		values["sortOrder"] = cmd.String("sort-order")
	}
	if cmd.IsSet("include-info") {
		values["includeInfo"] = cmd.Bool("include-info")
	}
	if cmd.IsSet("agent-schedule-id") {
		values["agentScheduleId"] = cmd.String("agent-schedule-id")
	}
	if cmd.IsSet("labels") {
		values["labels"] = cmd.String("labels")
	}
	if cmd.IsSet("tenant-id") {
		values["tenantId"] = cmd.String("tenant-id")
	}
	if cmd.IsSet("subject-id") {
		values["subjectId"] = cmd.String("subject-id")
	}
	if cmd.IsSet("widget-id") {
		values["widgetId"] = cmd.String("widget-id")
	}
	if cmd.IsSet("widget-session-id") {
		values["widgetSessionId"] = cmd.String("widget-session-id")
	}
	if err := decodeParams(values, &out.Params); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	return nil
}
