// Code generated by redwood. DO NOT EDIT.
package commands

import (
	cli "github.com/urfave/cli/v3"

	sdk "go.cadenya.com/cadenya-go"
)

const bodySchemaObjectivesCreateFeedback = "{\"$defs\":{\"CreateOperationMetadata\":{\"properties\":{\"externalId\":{\"description\":\"External ID for the operation (e.g., a workflow ID from an external system)\",\"type\":\"string\"},\"labels\":{\"additionalProperties\":{\"type\":\"string\"},\"description\":\"Key-value pairs for categorization and filtering. Values are 0-63\\n alphanumeric characters with \\\"-\\\", \\\"_\\\", or \\\".\\\" allowed between; keys\\n follow the same shape and additionally accept an optional DNS-subdomain\\n prefix (e.g. \\\"cadenya.com/\\\") of at most 253 characters.\\n Examples: {\\\"priority\\\": \\\"high\\\", \\\"source\\\": \\\"api\\\", \\\"workflow\\\": \\\"onboarding\\\"}\",\"type\":\"object\"}},\"type\":\"object\"},\"ObjectiveFeedbackData\":{\"properties\":{\"comment\":{\"description\":\"Optional human-readable comment explaining the feedback\",\"type\":\"string\"},\"score\":{\"description\":\"A score between -1.0 and 1.0 representing the quality of the objective's execution.\\n -1.0 is the worst possible score, 0.0 is neutral, and 1.0 is the best.\",\"type\":\"number\"}},\"type\":\"object\"}},\"properties\":{\"data\":{\"$ref\":\"ObjectiveFeedbackData\"},\"metadata\":{\"$ref\":\"CreateOperationMetadata\"}},\"required\":[\"metadata\",\"data\"],\"type\":\"object\"}"

// ObjectivesCreateFeedbackConversion is the typed request produced from one urfave command.
type ObjectivesCreateFeedbackConversion struct {
	Params sdk.ObjectiveCreateFeedbackParams
	Body   any
}

// ConvertObjectivesCreateFeedback reads urfave values according to Redwood's operation IR.
func ConvertObjectivesCreateFeedback(cmd *cli.Command, out *ObjectivesCreateFeedbackConversion) error {
	values := map[string]any{}
	if cmd.IsSet("workspace-id") {
		values["workspaceId"] = cmd.String("workspace-id")
	}
	_schema := parseBodySchema(bodySchemaObjectivesCreateFeedback)
	_body := newBodyBuilder()
	_strict := cmd.Bool("strict")
	var _rawBody any
	if cmd.IsSet("file") {
		if err := _body.applyFile("file", cmd.String("file"), _schema, _strict); err != nil {
			return cli.Exit(err.Error(), 2)
		}
	}
	if cmd.IsSet("metadata") {
		if err := _body.applyDoc("metadata", []string{"metadata"}, cmd.String("metadata"), _schema, _strict); err != nil {
			return cli.Exit(err.Error(), 2)
		}
	}
	if cmd.IsSet("data") {
		if err := _body.applyDoc("data", []string{"data"}, cmd.String("data"), _schema, _strict); err != nil {
			return cli.Exit(err.Error(), 2)
		}
	}
	if cmd.IsSet("label") {
		if err := _body.applyEntries("label", []string{"metadata", "labels"}, cmd.StringSlice("label"), scalarString, nil); err != nil {
			return cli.Exit(err.Error(), 2)
		}
	}
	if cmd.IsSet("external-id") {
		_v, err := stringArg("external-id", cmd.String("external-id"))
		if err != nil {
			return cli.Exit(err.Error(), 2)
		}
		if err := _body.set("external-id", []string{"metadata", "externalId"}, _v); err != nil {
			return cli.Exit(err.Error(), 2)
		}
	}
	if cmd.IsSet("data-score") {
		if err := _body.set("data-score", []string{"data", "score"}, cmd.Float32("data-score")); err != nil {
			return cli.Exit(err.Error(), 2)
		}
	}
	if cmd.IsSet("data-comment") {
		_v, err := stringArg("data-comment", cmd.String("data-comment"))
		if err != nil {
			return cli.Exit(err.Error(), 2)
		}
		if err := _body.set("data-comment", []string{"data", "comment"}, _v); err != nil {
			return cli.Exit(err.Error(), 2)
		}
	}
	if err := _body.finish(_schema, map[string]string{"metadata": "--metadata", "metadata.labels": "--label", "metadata.externalId": "--external-id", "data": "--data", "data.score": "--data-score", "data.comment": "--data-comment"}, _strict); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	_ = _rawBody
	for _k, _v := range _body.body {
		values[_k] = _v
	}
	if err := decodeParams(values, &out.Params); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	out.Body = _body.body
	return nil
}
