// Code generated by redwood. DO NOT EDIT.
package commands

import (
	cli "github.com/urfave/cli/v3"

	sdk "go.cadenya.com/cadenya-go"
)

const bodySchemaObjectivesDenyToolCall = "{\"$defs\":{},\"properties\":{\"memo\":{\"type\":\"string\"}},\"type\":\"object\"}"

// ObjectivesDenyToolCallConversion is the typed request produced from one urfave command.
type ObjectivesDenyToolCallConversion struct {
	Params sdk.ObjectiveDenyToolCallParams
	Body   any
}

// ConvertObjectivesDenyToolCall reads urfave values according to Redwood's operation IR.
func ConvertObjectivesDenyToolCall(cmd *cli.Command, out *ObjectivesDenyToolCallConversion) error {
	values := map[string]any{}
	if cmd.IsSet("workspace-id") {
		values["workspaceId"] = cmd.String("workspace-id")
	}
	_schema := parseBodySchema(bodySchemaObjectivesDenyToolCall)
	_body := newBodyBuilder()
	_strict := cmd.Bool("strict")
	var _rawBody any
	if cmd.IsSet("file") {
		if err := _body.applyFile("file", cmd.String("file"), _schema, _strict); err != nil {
			return cli.Exit(err.Error(), 2)
		}
	}
	if cmd.IsSet("memo") {
		_v, err := stringArg("memo", cmd.String("memo"))
		if err != nil {
			return cli.Exit(err.Error(), 2)
		}
		if err := _body.set("memo", []string{"memo"}, _v); err != nil {
			return cli.Exit(err.Error(), 2)
		}
	}
	if err := _body.finish(_schema, map[string]string{"memo": "--memo"}, _strict); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	_ = _rawBody
	for _k, _v := range _body.body {
		values[_k] = _v
	}
	if err := decodeParams(values, &out.Params); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	out.Body = _body.body
	return nil
}
