// Code generated by redwood. DO NOT EDIT.
package commands

import (
	cli "github.com/urfave/cli/v3"

	sdk "go.cadenya.com/cadenya-go"
)

// ObjectivesListToolCallsConversion is the typed request produced from one urfave command.
type ObjectivesListToolCallsConversion struct {
	Params sdk.ObjectiveListToolCallsParams
	Body   any
}

// ConvertObjectivesListToolCalls reads urfave values according to Redwood's operation IR.
func ConvertObjectivesListToolCalls(cmd *cli.Command, out *ObjectivesListToolCallsConversion) error {
	values := map[string]any{}
	if cmd.IsSet("workspace-id") {
		values["workspaceId"] = cmd.String("workspace-id")
	}
	if cmd.IsSet("limit") {
		values["limit"] = cmd.Int32("limit")
	}
	if cmd.IsSet("cursor") {
		values["cursor"] = cmd.String("cursor")
	}
	if cmd.IsSet("status") {
		values["status"] = cmd.String("status")
	}
	if cmd.IsSet("include-info") {
		values["includeInfo"] = cmd.Bool("include-info")
	}
	if cmd.IsSet("execution-status") {
		values["executionStatus"] = cmd.String("execution-status")
	}
	if cmd.IsSet("labels") {
		values["labels"] = cmd.String("labels")
	}
	if err := decodeParams(values, &out.Params); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	return nil
}
