// Code generated by redwood. DO NOT EDIT.
package commands

import (
	cli "github.com/urfave/cli/v3"

	sdk "go.cadenya.com/cadenya-go"
)

// ToolSearchSearchOrSetsConversion is the typed request produced from one urfave command.
type ToolSearchSearchOrSetsConversion struct {
	Params sdk.ToolSearchSearchOrSetsParams
	Body   any
}

// ConvertToolSearchSearchOrSets reads urfave values according to Redwood's operation IR.
func ConvertToolSearchSearchOrSets(cmd *cli.Command, out *ToolSearchSearchOrSetsConversion) error {
	values := map[string]any{}
	if cmd.IsSet("workspace-id") {
		values["workspaceId"] = cmd.String("workspace-id")
	}
	if cmd.IsSet("query") {
		values["query"] = cmd.String("query")
	}
	if err := decodeParams(values, &out.Params); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	return nil
}
