// Code generated by redwood. DO NOT EDIT.
package commands

import (
	cli "github.com/urfave/cli/v3"

	sdk "go.cadenya.com/cadenya-go"
)

const bodySchemaWorkspaceAdminAddMember = "{\"$defs\":{},\"properties\":{\"email\":{\"type\":\"string\"},\"profileId\":{\"type\":\"string\"}},\"type\":\"object\"}"

// WorkspaceAdminAddMemberConversion is the typed request produced from one urfave command.
type WorkspaceAdminAddMemberConversion struct {
	Params sdk.WorkspaceAdminAddMemberParams
	Body   any
}

// ConvertWorkspaceAdminAddMember reads urfave values according to Redwood's operation IR.
func ConvertWorkspaceAdminAddMember(cmd *cli.Command, out *WorkspaceAdminAddMemberConversion) error {
	values := map[string]any{}
	if cmd.IsSet("workspace-id") {
		values["workspaceId"] = cmd.String("workspace-id")
	}
	_schema := parseBodySchema(bodySchemaWorkspaceAdminAddMember)
	_body := newBodyBuilder()
	_strict := cmd.Bool("strict")
	var _rawBody any
	if cmd.IsSet("file") {
		if err := _body.applyFile("file", cmd.String("file"), _schema, _strict); err != nil {
			return cli.Exit(err.Error(), 2)
		}
	}
	if cmd.IsSet("profile-id") {
		_v, err := stringArg("profile-id", cmd.String("profile-id"))
		if err != nil {
			return cli.Exit(err.Error(), 2)
		}
		if err := _body.set("profile-id", []string{"profileId"}, _v); err != nil {
			return cli.Exit(err.Error(), 2)
		}
	}
	if cmd.IsSet("email") {
		_v, err := stringArg("email", cmd.String("email"))
		if err != nil {
			return cli.Exit(err.Error(), 2)
		}
		if err := _body.set("email", []string{"email"}, _v); err != nil {
			return cli.Exit(err.Error(), 2)
		}
	}
	if err := _body.finish(_schema, map[string]string{"profileId": "--profile-id", "email": "--email"}, _strict); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	_ = _rawBody
	for _k, _v := range _body.body {
		values[_k] = _v
	}
	if err := decodeParams(values, &out.Params); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	out.Body = _body.body
	return nil
}
