// Code generated by redwood. DO NOT EDIT.
package commands

import (
	cli "github.com/urfave/cli/v3"

	sdk "go.cadenya.com/cadenya-go"
)

// WorkspaceAdminListAccountConversion is the typed request produced from one urfave command.
type WorkspaceAdminListAccountConversion struct {
	Params sdk.WorkspaceAdminListAccountParams
	Body   any
}

// ConvertWorkspaceAdminListAccount reads urfave values according to Redwood's operation IR.
func ConvertWorkspaceAdminListAccount(cmd *cli.Command, out *WorkspaceAdminListAccountConversion) error {
	values := map[string]any{}
	if cmd.IsSet("limit") {
		values["limit"] = cmd.Int32("limit")
	}
	if cmd.IsSet("cursor") {
		values["cursor"] = cmd.String("cursor")
	}
	if cmd.IsSet("include-archived") {
		values["includeArchived"] = cmd.Bool("include-archived")
	}
	if cmd.IsSet("labels") {
		values["labels"] = cmd.String("labels")
	}
	if err := decodeParams(values, &out.Params); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	return nil
}
