// Code generated by redwood. DO NOT EDIT.
package commands

import (
	cli "github.com/urfave/cli/v3"

	sdk "go.cadenya.com/cadenya-go"
)

// WorkspaceAdminListMembersConversion is the typed request produced from one urfave command.
type WorkspaceAdminListMembersConversion struct {
	Params sdk.WorkspaceAdminListMembersParams
	Body   any
}

// ConvertWorkspaceAdminListMembers reads urfave values according to Redwood's operation IR.
func ConvertWorkspaceAdminListMembers(cmd *cli.Command, out *WorkspaceAdminListMembersConversion) error {
	values := map[string]any{}
	if cmd.IsSet("workspace-id") {
		values["workspaceId"] = cmd.String("workspace-id")
	}
	if cmd.IsSet("limit") {
		values["limit"] = cmd.Int32("limit")
	}
	if cmd.IsSet("cursor") {
		values["cursor"] = cmd.String("cursor")
	}
	if err := decodeParams(values, &out.Params); err != nil {
		return cli.Exit(err.Error(), 2)
	}
	return nil
}
