#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}go.cadenya.com/cadenya-go,github.com/cadenya/cadenya-go-staging"

go run ./cmd/cadenya "$@"
